### ISSUE TITLE
Add "info" and "health" endpoints for all 2.0 Apps

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-app-starters-maven-plugins#27]
As a developer, I'd like to add and enable `/actuator/info` and `/actuator/health` endpoints to all 2.0 Apps. 

**Acceptance:**
Include `management.endpoints.web.exposure.include=health,info,bindings` as a property to all the Apps.

**Comment by sabbyanandan** [comment]
Also, disable security by default via `org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration`.

**Comment by sobychacko** [comment]
Fixed via: https://github.com/spring-cloud/spring-cloud-app-starters-maven-plugins/commit/371044efe78c9ad4eaa28eb5c146c7a5f647c91b
