### ISSUE TITLE
Package /resources to the generated Apps

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-app-starters-maven-plugins#28]

**Comment by tzolov** [comment]
The goal is to bundle inside the generated app starter jar, resources coming either from the App jar or from any third-part jar dependency. 

For this we can use the [maven-dependency-plugin#unpack](https://maven.apache.org/plugins/maven-dependency-plugin/unpack-mojo.html) to unpack resources (specified with the `<includes>` clause)  from selected dependency jar and copy the into App Starter classpath. 

The solution implements a `copyResource` configuration block in the `spring-cloud-stream-app-maven-plugin` configuration to add generating maven-dependency-plugin definition in the generated App Starter's poms
For example adding the following `copyResources` section in the `spring-cloud-stream-app-maven-plugin` configuration:
```
<copyResources>
	<copyResource>
		<groupId>${project.groupId}</groupId>
		<artifactId>coap-app-starters-common</artifactId>
		<version>${project.version}</version>
		<includes>clientKeyStore.jks,cacerts</includes>
	</copyResource>
</copyResources>
```
Would result into adding `maven-dependency-plugin` to the pom of the generated app starter:
```
      <plugin>
        <groupId>maven-dependency-plugin</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>unpack</goal>
            </goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>org.springframework.cloud.stream.app</groupId>
                  <artifactId>coap-app-starters-common</artifactId>
                  <version>2.0.0.BUILD-SNAPSHOT</version>
                  <includes>clientKeyStore.jks,cacerts</includes>
                </artifactItem>
              </artifactItems>
              <outputDirectory>${project.build.directory}/classes/</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
```
The result AppStarter jar will contain the `clientKeyStore.jks` and `cacerts` under `BOOT-INF/classes/`
