### ISSUE TITLE
Remove SecurityAutoConfiguration exclusion for generated apps

### ISSUE THREAD

**Issue by tzolov** [spring-cloud/spring-cloud-app-starters-maven-plugins#36]
The Spring Boot 2.1.x [ManagementWebSecurityConfigurerAdapter](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/security/servlet/ManagementWebSecurityConfigurerAdapter.java) opens the `health` and `info` entry points by default. 
Since those are sufficient for allowing SCDF server to manage the monitor the SCSt apps, there is no need to disable the entire security by excluding `SecurityAutoConfiguration` 

Affects: `spring-cloud-stream-app-maven-plugin`

**Comment by tzolov** [comment]
Related to https://github.com/spring-cloud-stream-app-starters/app-starters-release/issues/161

**Comment by tzolov** [comment]
@artembilan we need to check the accessibility of the `bindings` actuator too

**Comment by artembilan** [comment]
> we need to check the accessibility of the bindings actuator too

Do you mean in your generic test-case?

Or do you it is not covered with that new `ManagementWebSecurityAutoConfiguration` in Spring Boot?

Let's handle it in the issue in `core` or already in your PR on the matter!
